### ISSUE TITLE
fetchFactoryPools() failing for Arbitrum

### ISSUE THREAD

**Issue by riordant** [curvefi/curve-api#303]
```
await curve.init('JsonRpc', 
       { url: $RPC_URL_ARBITRUM }, 
       { chainId: 42161 }
);
await curve.fetchFactoryPools();
```

Was working, now returns:
```
/home/project/node_modules/@ethersproject/abi/src.ts/interface.ts:100
        defineReadOnly(this, "fragments", abi.map((fragment) => {
                                              ^
TypeError: Cannot read properties of undefined (reading 'map')
    at new Interface (/home/riordant/Repositories/Orgs/Spool/test/SpoolAnalytics/node_modules/@ethersproject/abi/src.ts/interface.ts:100:47)
    at BaseContract.getInterface (/home/riordant/Repositories/Orgs/Spool/test/SpoolAnalytics/node_modules/@ethersproject/contracts/src.ts/index.ts:820:16)
    at Contract.BaseContract (/home/riordant/Repositories/Orgs/Spool/test/SpoolAnalytics/node_modules/@ethersproject/contracts/src.ts/index.ts:662:95)
    at new Contract (/home/riordant/Repositories/Orgs/Spool/test/SpoolAnalytics/node_modules/@ethersproject/contracts/lib/index.js:1053:42)
    at /home/riordant/Repositories/Orgs/Spool/test/SpoolAnalytics/node_modules/@curvefi/api/lib/factory/factory-api.js:90:27
    at Array.forEach (<anonymous>)
    at Curve.setFactorySwapContracts (/home/riordant/Repositories/Orgs/Spool/test/SpoolAnalytics/node_modules/@curvefi/api/lib/factory/factory-api.js:87:21)
    at Curve.<anonymous> (/home/riordant/Repositories/Orgs/Spool/test/SpoolAnalytics/node_modules/@curvefi/api/lib/factory/factory-api.js:162:45)
    at step (/home/riordant/Repositories/Orgs/Spool/test/SpoolAnalytics/node_modules/@curvefi/api/lib/factory/factory-api.js:44:23)
    at Object.next (/home/riordant/Repositories/Orgs/Spool/test/SpoolAnalytics/node_modules/@curvefi/api/lib/factory/factory-api.js:25:53)
```

**Comment by philippe-git** [comment]
Just seeing this now, but this is where you should report this issue: https://github.com/curvefi/curve-js
